version: '3'

services:
  fortune-api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./fortune_books:/app/fortune_books
      - ./chroma_db:/app/chroma_db
    environment:
      - API_ROOT_PATH=/api
    command: uvicorn fortune_main:app --host 0.0.0.0 --port 8000 --root-path /api

  fortune-app:
    build: ./app
    ports:
      - "8501:8501"
    depends_on:
      - fortune-api
    environment:
      - API_URL=http://fortune-api:8000/api

volumes:
  chroma_db:
